// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2FYUp5_4ihZnzpVbFLRqsDXDH_XhRuUY',
    appId: '1:1097447189844:web:9e8673e5ace4d6538aecc1',
    messagingSenderId: '1097447189844',
    projectId: 'event-app-50285',
    authDomain: 'event-app-50285.firebaseapp.com',
    storageBucket: 'event-app-50285.firebasestorage.app',
    measurementId: 'G-3VBSJGYPZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdArV5djuS5zmQ89J6lBkHG14y6KmVYqo',
    appId: '1:1097447189844:android:c203da809f5d34fc8aecc1',
    messagingSenderId: '1097447189844',
    projectId: 'event-app-50285',
    storageBucket: 'event-app-50285.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9AbuvpWmi5TeRNHMuCsMiOxTY3zs-lvI',
    appId: '1:1097447189844:ios:80ebbd3071adb6f28aecc1',
    messagingSenderId: '1097447189844',
    projectId: 'event-app-50285',
    storageBucket: 'event-app-50285.firebasestorage.app',
    iosBundleId: 'com.example.eventApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9AbuvpWmi5TeRNHMuCsMiOxTY3zs-lvI',
    appId: '1:1097447189844:ios:80ebbd3071adb6f28aecc1',
    messagingSenderId: '1097447189844',
    projectId: 'event-app-50285',
    storageBucket: 'event-app-50285.firebasestorage.app',
    iosBundleId: 'com.example.eventApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2FYUp5_4ihZnzpVbFLRqsDXDH_XhRuUY',
    appId: '1:1097447189844:web:2573b7e6220346a78aecc1',
    messagingSenderId: '1097447189844',
    projectId: 'event-app-50285',
    authDomain: 'event-app-50285.firebaseapp.com',
    storageBucket: 'event-app-50285.firebasestorage.app',
    measurementId: 'G-8FK4P9J6PW',
  );
}
